### ISSUE TITLE
Full profile card not opening when clicking on any Personal or Office cards

### ISSUE THREAD

**Issue by rchristenson** [topcoderinc/mjolnir-web#74]
### OS and Browser Details ###
Win 10 Microsoft Edge 41.16299.15.0 Dell XPS

### Screen Name where the issue occurs ###
https://mjolnir-web-prototype.herokuapp.com/profiles

### Exact Reproduction Steps ###
1. Click on profile card to expand it into a full profile/resume view
2. Nothing happens

### Actual  Result ###
*Enter the Actual result here.*

### Expected Result ###
When clicking on any card or profile it should fully expand into the full profile/resume view

### Screenshots/Video ###
*Paste screenshots here. For video, compress and attach*
![image](https://user-images.githubusercontent.com/31657407/35927712-603abb42-0bf9-11e8-924e-a3022806fb2c.png)

**Comment by mahestro** [comment]
Since this is a data-mockedup product (no real data - just clickable flow), we added two spots where profiles can be viewed from:

1. How to open Employer Profile view edit mode: login as employer (user: sss@sss.sss/ pass: sss) or create a employer profile, go to menu (top left burger menu), click the pencil icon on the profile http://take.ms/wGV1X
2. How to open Employer Profile view read mode: create an employee profile, click the displayed card on the dashboard http://take.ms/RHtMi

cc @rchristenson - closing.
